# Site settings
title: Kevin Hou's Blog
email: kevin.ch.hou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming, wood, and anything that comes to my mind.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://khou22.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  khou22

# Build settings
markdown: kramdown
