# Site settings
title: Kevin Hou
author:
  login: khou22
  email: kevin.ch.hou@gmail.com
  display_name: Kevin Hou
  first_name: Kevin
  last_name: Hou
location: San Francisco Bay Area
school: Lick-Wilmerding High School
email: kevin.ch.hou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kevin Hou's portfolio and blog about programming, wood, design, and photography. @khou22 Princeton Class of 2020. Lick-Wilmerding High School Class of 2016. San Francisco Bay Area.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://khou22.github.io" # the base hostname & protocol for your site

# External links
twitter_username: kevinhou22
github_username:  khou22
LinkedIn_url: "https://www.linkedin.com/in/kevinhou22"
portfolio_url: "http://kevinhou.wix.com/projects"
youtube_url: "https://youtube.com/kevinhou22"
flickr_url: "https://www.flickr.com/photos/khou22/albums"
vsco_url: "http://vsco.co/khou22/"
school_profile: "https://www.princeton.edu/main/"

gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-feed, jekyll-autoprefixer]

# Build settings
markdown: kramdown
paginate: 15 # Number of blog posts per page when browsing
paginate_path: "/blog/page:num/"

autoprefixer:
    only_production: true

# SEO Tagging
twitter:
  username: kevinhou22
social:
  name: Kevin Hou
  links:
    - https://twitter.com/kevinhou22
    - https://www.linkedin.com/in/kevinhou22
    - https://github.com/khou22
# google_site_verification:

# Bug fixes
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/
